//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReServeAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Reservation_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Table_ID { get; set; }
    
        public virtual Restaurant_Table Restaurant_Table { get; set; }
        public virtual User User { get; set; }
    }
}
