<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="reServe-HostessPage.aspx.cs" Inherits="ReServeAPI_v2._0.reServe_HostessPage" %>

<!DOCTYPE html>
<html>
<head>
    <title>ReServe - Hostess Page</title>
    <!--#include file="includes/header.inc"-->

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" type="text/javascript"></script>
    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/start/jquery-ui.css" rel="stylesheet" type="text/css" />

    <script type="text/javascript">
        $(function () {
            $(document.getElementById('viewBtn')).click(function () {
                ShowPopup();
                return false;
            });
        });
        function ShowPopup() {
            $(document.getElementById('dialog')).dialog({
                title: "GridView",
                width: 450,
                buttons: {
                    Ok: function () {
                        $(this).dialog('close');
                    }
                },
                modal: true
            });
            $(this).dialog('open');
        }
    </script>

    <style>
        .ui-widget {
            font-family: Verdana,Arial,sans-serif;
            font-size: .8em;
        }

        .ui-widget-content {
            background: #F9F9F9;
            border: 1px solid #90d93f;
            color: #222222;
        }

        .ui-dialog {
            left: 0;
            outline: 0 none;
            padding: 0 !important;
            position: absolute;
            top: 0;
        }

        #success {
            padding: 0;
            margin: 0;
        }

        .ui-dialog .ui-dialog-content {
            background: none repeat scroll 0 0 transparent;
            border: 0 none;
            overflow: auto;
            position: relative;
            padding: 0 !important;
        }

        .ui-widget-header {
            background: #b0de78;
            border: 0;
            color: #fff;
            font-weight: normal;
        }

        .ui-dialog .ui-dialog-titlebar {
            padding: 0.1em .5em;
            position: relative;
            font-size: 1em;
        }

        .oval {
            height: 100px;
            width: 200px;
            background-color: #555;
            border-radius: 50%;
        }

        .table {
            background: lightblue;
        }

        .textBox {
            height: 25px;
            width: 30px;
            position: relative;
            top: 10%;
            left: 5%;
        }
    </style>
</head>

<body>
    <!--#include file="includes/navbar-restaurant.inc"-->

    <!--#include file="includes/imagebar.inc"-->

    <!-- Page content -->
    <form id="form1" runat="server">
        <div class="container">
            <div class="row">
                <h2>Hostess Page</h2>
            </div>
            <div class="row">
                <p>Quickly manage all reservations from this page!</p>
            </div>

            <div class="row">
                <div class="col-25">
                    <asp:PlaceHolder ID="placeholder" runat="server"></asp:PlaceHolder>
                </div>

            </div>
            <div class="row">
                <div id="dialog" style="display: none">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateSelectButton="false" AllowPaging="false">
                        <Columns>
                            <asp:BoundField ItemStyle-Width="150px" DataField="Restaurant" HeaderText="Restaurant" />
                            <asp:BoundField ItemStyle-Width="150px" DataField="DateTime" HeaderText="Reservation Time" />
                        </Columns>
                    </asp:GridView>
                </div>


                <asp:Button ID="viewBtn" runat="server" Text="View Current Reservations" />
                <asp:Button ID="makeBtn" runat="server" Text="Make a Reservation" />
                <asp:Button ID="deleteBtn" runat="server" Text="Delete a Reservation" />
            </div>
        </div>
    </form>

    <!--#include file="includes/footer.inc"-->
</body>
</html>
