<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="reServe-RestaurantListOfEmployess.aspx.cs" Inherits="ReServeAPI_v2._0.reServe_RestaurantListOfEmployess" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Add Employee</title>
    <!--#include file="includes/header.inc"-->
</head>
<body>
    <!--#include file="includes/navbar-restaurant.inc"-->

    <!--#include file="includes/imagebar.inc"-->
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" AutoGenerateSelectButton="false" AllowPaging="false">
                <Columns>
                    <asp:BoundField ItemStyle-Width="150px" DataField="Name" HeaderText="Employee Name" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="Email" HeaderText="Employee Email" />
                </Columns>
            </asp:GridView>

            <div class="col-75 right">
                <asp:Button ID="addEmployeeBtn" runat="server" Text="Add Employee" OnClick="addEmployee" />
            </div>
        </div>
    </form>
    <!--#include file="includes/footer.inc"-->
</body>
</html>
