//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReServeAPI_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant_Table()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Table_ID { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Restaurant_ID { get; set; }
        public Nullable<int> Coord_X { get; set; }
        public Nullable<int> Coord_Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
