USE [master]
GO
/****** Object:  Database [ReServe]    Script Date: 9/18/2019 9:20:23 PM ******/
CREATE DATABASE [ReServe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ReServe', FILENAME = N'C:\ReServe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ReServe_log', FILENAME = N'C:\ReServe.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ReServe] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ReServe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ReServe] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [ReServe] SET ANSI_NULLS ON 
GO
ALTER DATABASE [ReServe] SET ANSI_PADDING ON 
GO
ALTER DATABASE [ReServe] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [ReServe] SET ARITHABORT ON 
GO
ALTER DATABASE [ReServe] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ReServe] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ReServe] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ReServe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ReServe] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [ReServe] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [ReServe] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ReServe] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [ReServe] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ReServe] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ReServe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ReServe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ReServe] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ReServe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ReServe] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ReServe] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ReServe] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ReServe] SET RECOVERY FULL 
GO
ALTER DATABASE [ReServe] SET  MULTI_USER 
GO
ALTER DATABASE [ReServe] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ReServe] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ReServe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ReServe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ReServe] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ReServe] SET QUERY_STORE = OFF
GO
USE [ReServe]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [ReServe]
GO
/****** Object:  Table [dbo].[Employees]    Script Date: 9/18/2019 9:20:23 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[Employee_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NULL,
	[Restaurant_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Employee_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Managers]    Script Date: 9/18/2019 9:20:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Managers](
	[Manager_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NOT NULL,
	[Restaurant_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Manager_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservations]    Script Date: 9/18/2019 9:20:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservations](
	[Reservation_ID] [int] NOT NULL,
	[User_ID] [int] NOT NULL,
	[Restaurant_ID] [int] NOT NULL,
	[Party_Size] [tinyint] NOT NULL,
	[Time] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Reservation_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Restaurant]    Script Date: 9/18/2019 9:20:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Restaurant](
	[Restaurant_ID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](12) NOT NULL,
	[Restaurant_Name] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Restaurant_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Restaurant_2]    Script Date: 9/18/2019 9:20:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Restaurant_2](
	[Restaurant_ID] [int] NOT NULL,
	[Manager_ID] [int] NOT NULL,
	[Gps_Lat] [float] NULL,
	[Gps_Long] [float] NULL,
	[Name] [varchar](100) NOT NULL,
	[Capacity] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[Restaurant_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 9/18/2019 9:20:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[User_ID] [int] IDENTITY(1,1) NOT NULL,
	[First_Name] [varchar](30) NOT NULL,
	[Last_Name] [varchar](30) NOT NULL,
	[Email] [varchar](30) NOT NULL,
	[Password] [varchar](12) NOT NULL,
	[Manager] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Restaurant] ON 

INSERT [dbo].[Restaurant] ([Restaurant_ID], [Email], [Password], [Restaurant_Name]) VALUES (1, N'hi', N'hi', N'hi')
INSERT [dbo].[Restaurant] ([Restaurant_ID], [Email], [Password], [Restaurant_Name]) VALUES (2, N'test@test.com', N'test123', N'test')
SET IDENTITY_INSERT [dbo].[Restaurant] OFF
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_ToRestaurant_2] FOREIGN KEY([Restaurant_ID])
REFERENCES [dbo].[Restaurant_2] ([Restaurant_ID])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_ToRestaurant_2]
GO
ALTER TABLE [dbo].[Employees]  WITH CHECK ADD  CONSTRAINT [FK_Employees_ToUsers] FOREIGN KEY([User_ID])
REFERENCES [dbo].[Users] ([User_ID])
GO
ALTER TABLE [dbo].[Employees] CHECK CONSTRAINT [FK_Employees_ToUsers]
GO
ALTER TABLE [dbo].[Managers]  WITH CHECK ADD  CONSTRAINT [FK_Managers_ToUsers] FOREIGN KEY([User_ID])
REFERENCES [dbo].[Users] ([User_ID])
GO
ALTER TABLE [dbo].[Managers] CHECK CONSTRAINT [FK_Managers_ToUsers]
GO
ALTER TABLE [dbo].[Reservations]  WITH CHECK ADD  CONSTRAINT [FK_Reservations_ToUsers] FOREIGN KEY([User_ID])
REFERENCES [dbo].[Users] ([User_ID])
GO
ALTER TABLE [dbo].[Reservations] CHECK CONSTRAINT [FK_Reservations_ToUsers]
GO
ALTER TABLE [dbo].[Restaurant_2]  WITH CHECK ADD  CONSTRAINT [FK_Restaurant_2_ToManagers] FOREIGN KEY([Manager_ID])
REFERENCES [dbo].[Managers] ([Manager_ID])
GO
ALTER TABLE [dbo].[Restaurant_2] CHECK CONSTRAINT [FK_Restaurant_2_ToManagers]
GO
USE [master]
GO
ALTER DATABASE [ReServe] SET  READ_WRITE 
GO
