<!-- Navbar -->
    <nav id="rs-main-nav" class="navbar navbar-expand-md navbar-dark fixed-top">

        <!-- Brand = Highlights the the name of the project -->
		<!-- Brand = Highlights the the name of the project -->
		<a class="navbar-brand" href="#">
			<img src="images\tea-time-32-292243.png" alt="I'm a little teapot">
		</a>
        <a class="navbar-brand" href="reServe-MainPage.aspx">ReServe</a>

        <!-- Collapse toggler = Creates hamburger menu for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--Navbar Links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="#">Add Employee</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Hostess Page</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Account Information</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Table Configurations</a>
				</li>

				<!-- Dropdown -->
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
						Reservations
					</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="#">Make Reservations</a>
						<a class="dropdown-item" href="#">View Reservations</a>
					</div>
				</li>
			</ul>
		</div>
    </nav>