<!-- Navbar main doesn't actually include any navigation -->
    <nav id="rs-main-nav" class="navbar navbar-expand-md navbar-dark fixed-top">

        <!-- Brand = Highlights the the name of the project -->
		<a class="navbar-brand" href="#">
			<img src="images\tea-time-32-292243.png" alt="I'm a little teapot">
		</a>
        <a class="navbar-brand" href="#">ReServe</a>

        <!-- Collapse toggler = Creates hamburger menu for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        
    </nav>