<!-- Navbar -->
    <nav id="rs-main-nav" class="navbar navbar-expand-md navbar-dark fixed-top">

        <!-- Brand = Highlights the the name of the project -->
        <a class="navbar-brand" href="ReServe-Main.html">ReServe</a>

        <!-- Collapse toggler = Creates hamburger menu for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--Navbar Links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li id="rs-nav-link" class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Restaurant
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Sign Up</a>
                        <a class="dropdown-item" href="#">Log In</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Customer
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Sign Up</a>
                        <a class="dropdown-item" href="#">Log In</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>