<!-- Navbar main only contains logo and login link -->
    <nav id="rs-main-nav" class="navbar navbar-expand-md navbar-dark fixed-top">

        <!-- Brand = Highlights the the name of the project -->
		<a class="navbar-brand" href="#">
			<img src="images\tea-time-32-292243.png" alt="I'm a little teapot">
		</a>
        <a class="navbar-brand" href="reServe-MainPage.aspx">ReServe</a>

        <!-- Collapse toggler = Creates hamburger menu for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

		<!--Navbar Links -->
        <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
            <ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="reServe-Login.aspx">Login</a>
				</li>
			</ul>
		</div>
     </nav>