<!-- Navbar -->
    <nav id="rs-main-nav" class="navbar navbar-expand-md navbar-dark fixed-top">

        <!-- Brand = Highlights the the name of the project -->
        <a class="navbar-brand" href="ReServe-Main.html">ReServe</a>

        <!-- Collapse toggler = Creates hamburger menu for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!--Navbar Links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Link</a>
				</li>
			</ul>
		</div>
    </nav>