//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReServeAPI_v2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Deal_ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Restaurant_ID { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
